### ISSUE TITLE
Feature Request: Show Sent Origin in Overview

### ISSUE THREAD

**Issue by emanuelduss** [ybieri/Additional_CORS_Checks#1]
Hey Yves

Nice extension 😀👍

It would be nice, if the sent origin would be shown in the overview table:
![image](https://user-images.githubusercontent.com/438188/142450036-c458b1f6-7506-4ad4-b85e-a121b08a89f9.png)

This would make it easier to see the misconfigurations and the documentation of the tested origins.

THX & have a good time,
Mänu

**Comment by ybieri** [comment]
Implemented in 6b072bf20ff7ee41bea7885796d95b18cd412bdf.
