### ISSUE TITLE
Finding entries inserted in the Burp Dashboard only for Automatic mode

### ISSUE THREAD

**Issue by halfluke** [ybieri/Additional_CORS_Checks#2]
I am experiencing that if I send a call to the extension and scan it manually from there, the CORS misconfiguration that are found, are not added to the Burp Dashboard, while they are added when "Activate CORS" is checked. Is this intended? It would be nicer if they were added in both automatic and manual mode.

**Comment by ybieri** [comment]
That's not intended. I'll add it to the manual mode as well once I get some spare time for it!

**Comment by ybieri** [comment]
Implemented in 6b072bf20ff7ee41bea7885796d95b18cd412bdf. Will do PR to the Portswigger branch soon.

**Comment by halfluke** [comment]
Great stuff and thank you! Are you going to update the jar in your repo as well?

**Comment by ybieri** [comment]
I added the JAR file: https://github.com/ybieri/Additional_CORS_Checks/blob/master/additional-cors-checks.jar
I also created a PR to Portswigger. As soon as it's reviewed, the changes should also be available through the Bapp store.
